=begin
#Ergast F1 DB OpenAPI Spec

#This is a *partial* definition of the [Ergast F1 API](https://ergast.com/mrd/) in the OpenAPI 3.0 specification. Of the the endpoints that are implemented here, the url paths and return data schemas are structured to match the structure currently used on the live Ergast API.     You should be able to use the as a starting point for [generating your client libraries](https://github.com/OpenAPITools/openapi-generator) for use with Ergast, or setting up your own API to use with a copy of the Ergast DB.   Some notes:   - This only defines the JSON data schema, not the XML version of the API return data - Outside of the year, most of the inline parameters used by the Ergast API are not defined here.    - The placeholder values for year are not currently implemented.

OpenAPI spec version: 1.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.34
=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/circuit'
require 'swagger_client/models/circuit_location'
require 'swagger_client/models/constructor'
require 'swagger_client/models/constructor_standings_by_year_response'
require 'swagger_client/models/constructor_standings_by_year_response_mr_data'
require 'swagger_client/models/constructor_standings_by_year_response_mr_data_standings_table'
require 'swagger_client/models/constructor_standings_by_year_response_mr_data_standings_table_constructor_standings'
require 'swagger_client/models/constructor_standings_by_year_response_mr_data_standings_table_standings_lists'
require 'swagger_client/models/constructors_by_year_response'
require 'swagger_client/models/constructors_by_year_response_mr_data'
require 'swagger_client/models/constructors_by_year_response_mr_data_constructor_table'
require 'swagger_client/models/driver'
require 'swagger_client/models/driver_standings_by_year_response'
require 'swagger_client/models/driver_standings_by_year_response_mr_data'
require 'swagger_client/models/driver_standings_by_year_response_mr_data_standings_table'
require 'swagger_client/models/driver_standings_by_year_response_mr_data_standings_table_driver_standings'
require 'swagger_client/models/driver_standings_by_year_response_mr_data_standings_table_standings_lists'
require 'swagger_client/models/race'
require 'swagger_client/models/result'
require 'swagger_client/models/result_fastest_lap'
require 'swagger_client/models/result_fastest_lap_average_speed'
require 'swagger_client/models/result_fastest_lap_time'
require 'swagger_client/models/result_time'
require 'swagger_client/models/results_by_year_response'
require 'swagger_client/models/results_by_year_response_mr_data'
require 'swagger_client/models/results_by_year_response_mr_data_race_table'
require 'swagger_client/models/season_by_year_response'
require 'swagger_client/models/season_by_year_response_mr_data'
require 'swagger_client/models/season_by_year_response_mr_data_race_table'

# APIs
require 'swagger_client/api/constructors_api'
require 'swagger_client/api/drivers_api'
require 'swagger_client/api/results_api'
require 'swagger_client/api/schedule_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
